### ISSUE TITLE
Garden Release

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#144]
This issue tracks the launch of our new onboarding flow and garden nodes.

---

* [x] git-server
  * [x] Git push support
    * [x] Track on push
    * [x] Quorum HEAD
    * [x] Set HEAD
    * [x] Create projects
      * [x] Project verification
    * [x] SSH-based authentication
  * [x] Git fetch support
    * [x] Gzip
  * [x] Git clone support
* [x] CLI
  * [x] Installation
    * [x] Debian packages
    * [x] Arch packages
  * [x] Command: `rad auth`
  * [x] Command: `rad init`
  * [x] Command: `rad publish`
  * [x] Command: `rad ls`
  * [x] Command: `rad show`
  * [x] Command: `rad ens`
    * [x] Shows URL to project on seed node
  * [x] Command: `rad sync`
    * [x] Push changes
    * [x] Fetch changes
      * [x] Verify
  * [x] Command: `rad track` (stretch)
  * [x] Command: `rad checkout` (stretch)
* [x] Web
  * [x] Branch browsing (`/projects/:urn/tree/:branch`)
    * [x] Project branch selection
  * [x] Peer browsing (`/projects/:urn/remotes/:peer/tree/`)
    * [x] Project peer selection
  * [x] Project page on seed (`/seeds/:seed/projects/:urn`)
  * [x] Quorum state
  * [x] Seed page
    * [x] Basic info
    * [x] Project listing
  * [x] New paths `/:user/:project` (#170) 
* [x] Seed node deployment
  * [x] maple.radicle.garden
  * [x] pine.radicle.garden
  * [x] willow.radicle.garden

**Comment by sebastinez** [comment]
@cloudhead should we eventually create a release for `radicle-interface` for this? Maybe a `1.1`? wdyt?

**Comment by cloudhead** [comment]
Yeah good idea.

**Comment by cloudhead** [comment]
Since the get started page will be its own repo, closing this now as completed.
