### ISSUE TITLE
User Identities

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#17]
## Objective
User and Orgs Identities require the display of their identities if registered. Using ENS every change to ones metadata requires a transaction to the corresponding contract.
We will work with the IDX protocol from ceramic to implement a way to more efficiently update the information.

### Lookup Priority
1. ENS Registrar
2. DID IDX on Ceramic
3. Ethereum Blockies

### Home
- [x] Search input should be able to also search for user identities and ETH addresses. (3114db12c1a7687ce722b5823da04815b36dcb82)
### User profile
- [x] Replace user addresses with resolved ENS names (if registered) (a9eebfa033bc4d53e6692e86e8caf46f30e8b5cf)
- [x] Tooltip with eth address for `Address` component when not showing address. (5c63c1da1b0d376b68af1b3830b6923fc866b1d7)
- [x] Instead of the Ethereum blockies a url avatar should be loaded if available (5c63c1da1b0d376b68af1b3830b6923fc866b1d7)
- [x] /users/:address page should show avatar, name, websites if available as shortcuts (b74943609d78a5b21fef02993e25b38d03b9b5ed)
- [x] EOA addresses should link to /users/:address page (5c63c1da1b0d376b68af1b3830b6923fc866b1d7)
- [x] The owner in the registration page should be resolved. (805ac0ddbbe9bc0e8476dd1b6af972ea8a7c4290)
- [x] Orgs listing should show avatars of orgs (552755a3b9e1bfd1e1d3ecb8d893a351a2423914)
- [x] Member list of orgs should resolve to available metadata (cb493801dcad5c6ec92dbd25c0ad4e2fef5eaccf)
- [x] Org details should show resolved owner and participants avatar and registered name (cb493801dcad5c6ec92dbd25c0ad4e2fef5eaccf)
- [x] Connect/Disconnect button in header should show avatar (or blockies) and ENS name if available (805ac0ddbbe9bc0e8476dd1b6af972ea8a7c4290)

### Improvements
- [x] Allow linking of CAIP10 Accounts to DIDs (dcdec8c8e1ba98b5a6473d21f8698c1a411fb4de)

## PR Implementations
1. Creation of user route with UI that shows user address and metadata. (#20)
2. Implementation of the IDX protocol #28 
3. Usage of resolved addresses and avatars in other parts of the app #44

**Comment by cloudhead** [comment]
Thoughts on where ENS can be integrated:

* Member list of orgs should resolve to the avatar + ENS name if available
* Connect/Disconnect button in header should show avatar (or blockies) and ENS name if available
* Resolver (search bar) should go to /users/ page if EOA or user ENS name is entered
* EOA addresses should link to /users/:address page
* /users/:address page should show avatar, name, websites if available

**Comment by cloudhead** [comment]
All done!
