### ISSUE TITLE
Project Browsing

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#18]
* [x] Project source browsing by ID + commit hash
* [x] Browse project without a commit hash
* [x] Error state when project is not found
* [x] Error state when project file is not found
* [x] Error state when project commit is not found
* [x] Render markdown files
* [x] Org view projects link to project page
* [x] Project view shows org context if available
* [x] When org context is available, verify commit hash against anchor
* [x] When anchor doesn't match project commit, show warning
* [x] Show project contributor count
* [x] Show project commit count
* [x] Show project maintainers
* [x] Show last commit message
* [x] Clicking on project name goes back to root
* [x] Preload blobs so UI doesn't flicker

## Nice to haves

* [ ] Horizontal scrollbars in blob view
* [x] #132
* [ ] #125
