### ISSUE TITLE
Issues from user session

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#24]
* [x] Rinkeby contract(s) deployment
* [x] Refresh balance on page reload
* [x] Register link in "not found" is not primary color
* [x] `Provided chainId "3" must match active chainId "3"`
* [x] Switching network doesn't update balance
* [x] Registration edit jumps around due to loading indicator
* [x] Show user what orgs he/she is a member of
* [x] Show user how much RAD the registration will cost
* [x] Overflow on /registrations/:name URLs looks ugly
* [x] Org avatars don't get resized properly
* [x] Trigger SetName transaction when org owner is Safe
* [x] Set custom org owner address during creation
* [x] Inputs should trim value to get rid of trailing whitespace
* [ ] #35
* [ ] #34
* [x] #33
* [ ] #36
