### ISSUE TITLE
Writing issues/comments through authentication with seed node

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#500]
Ok this issue will be a tracking issue to write down the design behind the writing of issues and comments through the web client

## Architecture
<insert draw.io image here>

## Goals
- Users should be able to create a new issue from the project page.
- Users should be able to create a comment on the main comment thread, inside a specific issue
- Users should be able to create a comment replying to a specific comment, aka creating a new discussion thread
- Users should be able to get a auth token with help of the CLI and the web client for authentication

### Web Client
- [x] Add a route that can be opened from the CLI with a unauthorized sessionId, publicKey and signature
- [x] This route should send a PUT request to the httpd to authorize the session
- [x] The authorized sessionId should be put on any header made to the local radicle-httpd.
- [x] Add issue creation
- [ ] Add comment or new discussions creation on an existing issue.
- [x] Add self and assigment of other users on an issue
- [x] Add selection of reactions on issues and comments

### CLI
- [x] Add a new command `rad web` command that generates a sessionId, signature and passes it to the web client

### httpd
- [x] Add endpoint for creating new issues
- [x] Add endpoint for creating new comments or discussions on existing issues
https://github.com/radicle-dev/heartwood/pull/260

**Comment by cloudhead** [comment]
I've put more thought into this, and I'm no longer sure whether we want to require users go through SIWE to do this, when it is a local node they are talking to. For remote nodes (if we have that use case) it makes sense. But for local nodes, we'd be forcing Metamask onto users just to talk to their local node.

That being said, most of the flow would be similar: you obtain an auth token somehow, then send that auth token in every request to http-api.

I think we should explore ways in which to obtain that auth token possibly via the CLI. For example I could imagine a command like `rad web` which would open a browser window with the app open pointing to your local node, and it would include in the URL an auth token that can be used to securely communicate with http-api.

There are other apps that work like this, so it's worth a bit of research, eg. how certain CLIs log you into websites. I think npm does this maybe?

**Comment by sebastinez** [comment]
Hey @cloudhead thanks for your feedback!

I agree with connecting to a local node through the CLI and steer away from using SIWE and specially any web3 extension just for connecting with a local node.

To connect with a local node I suggest:
- as you mentioned a CLI command e.g. `rad web`
- which generates a URL to be visited e.g. `https://app.radicle.xyz/login?type=cli/<auth token>`
  - the type param would allow us to eventually allow other login methods apart from CLI `siwe | yubikey` etc.
- When visiting the page the auth token would get saved in localStorage and used for an initial request to obtain some user identity information, like peer id, eventual ens profile, etc.
- From then on any request to the local node would send the auth token as part of the request header.
- While the local node would store the auth token, and verify each request similar to what we are doing currently with SIWE.

We probably would also want to drop the auth token after a specific amount of time.
And allow some way to logout and which would delete the token from localStorage and from the local node.

If I understand correctly, by connecting to a local node we would also allow the user to connect to their local RAD identity?
This would be nice to allow users create issues and comments with their identity instead of a seed node one.

**Comment by cloudhead** [comment]
> Hey @cloudhead thanks for your feedback!
> 
> I agree with connecting to a local node through the CLI and steer away from using SIWE and specially any web3 extension just for connecting with a local node.
> 
> To connect with a local node I suggest:
> 
>     * as you mentioned a CLI command e.g. `rad web`
> 

Yeah, almost wondering if it could be via `rad auth` :thinking: 

>     * which generates a URL to be visited e.g. `https://app.radicle.xyz/login?type=cli/<auth token>`
>       
Yeah.

>       * the type param would allow us to eventually allow other login methods apart from CLI `siwe | yubikey` etc.
Yeah.

>       * the auth token should be provided by the http-api and stored in the context session. The CLI should provide information to the http-api to authenticate the user, maybe some text signed by the user RAD key?
> 
Ok this part is a bit tricky; so the http-api *knows* who the current user is, via `Profile`. So actually I think the CLI could use a public API call to ask for an auth challenge (we have something like this in siwe) for the current public key, and sign that.

Then it would open the browser with (1) the public key, just for verification, and (2) the signature over the auth challenge. The browser would then provide both of those to the http-api, which would return an auth session token.

>     * When visiting the page the auth token would get saved in localStorage and used for an initial request to obtain some user identity information, like peer id, eventual ens profile, etc.
> 
Yeah.

>     * From then on any request to the local node would send the auth token as part of the request header.
> 
>     * While the local node would store the auth token, and verify each request similar to what we are doing currently with SIWE.
> 
Yeah.

> 
> We probably would also want to drop the auth token after a specific amount of time. And allow some way to logout and which would delete the token from localStorage and from the local node.
> 
> AFAIK, by connecting to a local node we would also allow the user to connect to their local RAD identity? This would be nice to allow users create issues and comments with their identity instead of a seed node one.
That's right, you'd control your local identity. There's only one identiy here, node == user.
